[package]
name = "crsql_text_crdt_fugue"
version = "0.1.0"
edition = "2021"
keywords = ["sqlite", "cr-sqlite", "crdt", "fugue", "text"]
license = "Apache 2"

[lib]
name = "crsql_text_crdt_fugue"
crate-type = ["rlib"]

[dependencies]
sqlite_nostd = { path="../sqlite-rs-embedded/sqlite_nostd" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
loadable_extension = ["sqlite_nostd/loadable_extension"]
static = ["sqlite_nostd/static"]
omit_load_extension = ["sqlite_nostd/omit_load_extension"]
